workflows:
  build_apk:
    name: Build IdleCult APK
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - keystore_group
      vars:
        PACKAGE_NAME: "com.example.idlecult"
    android_signing:
      keystore: $KEYSTORE
      keystore_password: $KEYSTORE_PASSWORD
      key_alias: $KEY_ALIAS
      key_password: $KEY_PASSWORD
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
